import type { Metadata } from "next";
import { Bai_Jamjuree } from "next/font/google";
import NavBar from "@/components/navigation/NavBar";
import { Footer } from "@/components/footer";
import { Toaster } from "react-hot-toast";
import SideNavigation from "@/components/navigation/SideNavigation";
import { ThemeProvider } from "@/components/theme-provider";
import "react-tooltip/dist/react-tooltip.css";
import "@smastrom/react-rating/style.css";
import {TanstackQueryClientProvider,ReduxStoreProvider} from "@/context";
import "./globals.css";

const bai_Jamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`relative ${bai_Jamjuree.className} mx-auto text-lg 2xl:text-xl`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <TanstackQueryClientProvider>
            <ReduxStoreProvider>
              <NavBar />
              <Toaster
                containerStyle={{
                  top: 40,
                }}
                toastOptions={{
                  className: "",
                  style: {
                    border: "1px solid #713200",
                    color: "#713200",
                  },
                }}
                position="top-center"
                reverseOrder={false}
              />
              <main className=""> {children}</main>
              <SideNavigation />
            </ReduxStoreProvider>
          </TanstackQueryClientProvider>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
