import type { Metadata } from "next";
import { Bai_Jamjuree } from "next/font/google";
import NavBar from "@/components/navbar/NavBar";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";

const bai_Jamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "300", "400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bai_Jamjuree.className} text-lg`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <NavBar />
        <main className="px-5">  {children}</main>
          </ThemeProvider>
      
      </body>
    </html>
  );
}
