import type { Metadata } from "next";
import { Bai_Jamjuree } from "next/font/google";
import NavBar from "@/components/navigation/NavBar";
import {Footer} from "@/components/footer";

import SideNavigation from "@/components/navigation/SideNavigation";
import { ThemeProvider } from "@/components/theme-provider";
import "react-tooltip/dist/react-tooltip.css";
import "@smastrom/react-rating/style.css";
import "./globals.css";
import TanstackQueryClientProvider from "@/components/shared/TanstackQueryClientProvider";

const bai_Jamjuree = Bai_Jamjuree({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bai_Jamjuree.className} text-lg`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <TanstackQueryClientProvider>
            <NavBar />
            <main className=""> {children}</main>
            <SideNavigation />
          </TanstackQueryClientProvider>
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
